name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x MedicalTranslator/gradlew

      - name: Build with Gradle
        # This command creates the debug APK file.
        run: ./MedicalTranslator/gradlew assembleDebug

      - name: Upload app-debug.apk
        # This new step saves the APK.
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: MedicalTranslator/app/build/outputs/apk/debug/app-debug.apk
          
